
# gram_parser_tab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'S\xc6\xa2T\x04\xa9\x07\x06\xd5WW\xaa\xb0.\xcd\xa6'
    
_lr_action_items = {'END':([7,8,9,10,12,],[-7,-6,11,-8,-5,]),'E':([5,7,8,9,10,12,],[10,-7,-6,10,-8,-5,]),'COLON':([1,],[5,]),'NAME':([0,3,4,5,6,7,8,9,10,11,12,],[1,1,-3,7,-2,-7,-6,7,-8,-4,-5,]),'$end':([2,3,4,6,11,],[0,-1,-3,-2,-4,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Symbols':([5,],[9,]),'Start':([0,],[2,]),'Symbol':([5,9,],[8,12,]),'Productions':([0,],[3,]),'Production':([0,3,],[4,6,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Start","S'",1,None,None,None),
  ('Start -> Productions','Start',1,'p_Start','/media/main/home/hendersont/stuff/Programming/PyOhio2011/pytdpp/gram_parser.py',151),
  ('Productions -> Productions Production','Productions',2,'p_Productions1','/media/main/home/hendersont/stuff/Programming/PyOhio2011/pytdpp/gram_parser.py',158),
  ('Productions -> Production','Productions',1,'p_Productions2','/media/main/home/hendersont/stuff/Programming/PyOhio2011/pytdpp/gram_parser.py',159),
  ('Production -> NAME COLON Symbols END','Production',4,'p_Production','/media/main/home/hendersont/stuff/Programming/PyOhio2011/pytdpp/gram_parser.py',161),
  ('Symbols -> Symbols Symbol','Symbols',2,'p_Symbols1','/media/main/home/hendersont/stuff/Programming/PyOhio2011/pytdpp/gram_parser.py',167),
  ('Symbols -> Symbol','Symbols',1,'p_Symbols2','/media/main/home/hendersont/stuff/Programming/PyOhio2011/pytdpp/gram_parser.py',171),
  ('Symbol -> NAME','Symbol',1,'p_Symbol1','/media/main/home/hendersont/stuff/Programming/PyOhio2011/pytdpp/gram_parser.py',175),
  ('Symbol -> E','Symbol',1,'p_Symbol2','/media/main/home/hendersont/stuff/Programming/PyOhio2011/pytdpp/gram_parser.py',183),
]
